### ISSUE TITLE
Please highlight the buttons in left sidebar

### ISSUE THREAD

**Issue by VarunAgw** [Xanashi/Icaros#23] opened 2021-08-26 09:27 UTC
![29322173-ebed825c-81dc-11e7-8355-451b0c4e0635 1](https://user-images.githubusercontent.com/4201835/130938045-d85db8c6-3cdb-443b-aef2-7ba4253296f8.png)

As you can see in the image, The buttons "Activated", "Enabled" are not so obvious since android phone usually use the whole area as navigation.

Either move them to bottom of left sidebar in a new section called "Toggle status" or do something else. I will click on that to switch to the tab, but I always toggling the status mistakinly

**Comment by Xanashi** [comment] 2022-06-24 11:33
Duplicate of #1

**Closed by Xanashi** 2022-06-24 11:33 UTC
