### ISSUE TITLE
Using "Thumbnailing" somehow makes Win10 forget its caches.

### ISSUE THREAD

**Issue by Mrfunreal** [Xanashi/Icaros#106] opened 2024-07-08 12:57 UTC
Heyo.

Anytime i use the Thumbnailing option, win10 somehow seems to forget it even has a cache.
When i reboot my pc (or just explorer.exe) it takes about 5-10 seconds to load all thumbnails once over. Especially when i'm using any kind of "Save as" or "Open file" window (Like on snipping tool, discord, or just opera to upload a picture). 
On those windows, it doesn't show any thumbnails at all, for a solid minute sometimes. Closing and reopening that window causes the thumbnails to be lost, requiring it to reload all of it for another solid minute.

The only files i'm thumbnailing are: psd, dds, tga, mkv, mp4, webm.
Caching is set to "Dynamic" if that makes a difference.
I used icaros' debug tool to generate both icaros and explorer caches for all my image folders in all available sizes, which took me about an hour to do, so i see no reason why it wouldn't load the thumbnails.

**Comment by Xanashi** [comment] 2024-07-10 11:14
It sounds like your Windows thumbnail cache has somehow become corrupt/stuck. 
I recommend that you try to completely clear the Windows cache, and then restart Explorer.
You can clear the cache on the Tools page in IcarosConfig.

I've seen this bug several times before, but I'm not sure what is causing it to happen. 
It is a Windows bug, so there is not really anything I can do from my end.

Icaros doesn't affect how File Explorer operates in any way, it just gives Explorer two libraries to call on when it's missing thumbnails or properties for several filetypes.

Also filling the Icaros Cache is much easier just using the built-in indexer on the Cache page of IcarosConfig.
Simply add your folders/drives on the Locations tab, and use the Build button in the Settings tab afterwards.
This will not fill the Windows thumbnail cache however, but should still speed up thumbnailing a lot.

**Comment by Xanashi** [comment] 2024-07-18 19:41
I'm going to close this ticket for now. Don't hesitate to reopen it if needed.

**Closed as completed by Xanashi** 2024-07-18 19:41 UTC

**Comment by Mrfunreal** [comment] 2024-07-26 14:16
Unfortunately, even after deleting and rebuilding the cache numerous times, ut doesn't help.
If i disable icaros and reboot the pc, everything works dandy, turning it back and and rebooting, breaks everything again.

Anyways. i tried using the indexer, and it is faster, but it still doesn't help that windows doesn't read any thumbnails anymore.

If it really is a windows bug, i guess there's nothing i can do but accept the fact that my won't get to use and thumbnails. Oh well.

**Comment by clsid2** [comment] 2024-07-26 14:48
Windows can clean the cache by itself. Here is tip to disable that:
https://www.winhelponline.com/blog/thumbnail-cache-automatically-deleted-windows-maintenance/

**Comment by Mrfunreal** [comment] 2024-07-26 14:52
I know about that and already used it. 
The problem is not the windows cache. That works a-okay if Icaros is turned off.

**Comment by clsid2** [comment] 2024-07-26 15:16
If a thumbnail is available in the Windows cache, then it would not be calling Icaros to generate a new one, unless Explorer somehow decides it needs to be refreshed. Icaros does not decide when to generate a thumbnail.

Windows thumbnail behavior has always been very erratic. It may regenerate thumbs when cache gets too large. Or it may randomly decide to regenerate when you add a new file to a folder.

Take a look at the Windows cache folder directly after a reboot to see if there are any size changes compared to before the reboot.

**Comment by Mrfunreal** [comment] 2024-07-26 15:48
I've been rebuilding the caches many, many times. the first thing I look for after a reboot is that file. And every time i do rebuild them, they slowly fill up and get bigger just like you'd expect.

The thing is that even if it has a cache, it ignores it and doesn't show anything for a while.
That is my whole issue, it has a cache and it isn't showing anything.

**Comment by clsid2** [comment] 2024-07-26 16:36
You are being unclear. You say it isn't showing anything, but you seem to mean it regenerates the thumbnail.

Please stop trying to manually build caches. Don't look at Icaros cache. The problem is with the Windows cache.

So look only at Windows cache. These are multiple files, not just one. Does its size change after reboot? Because if it is suddenly small again it means the cache did get cleared somehow.

Cleanup tools like CCleaner also can remove cache. So don't use that.

**Comment by Mrfunreal** [comment] 2024-07-27 12:45
I told you. The windows thumbnail cache works absolutely perfectly fine. 
All of its cache files are growing when they should.
I've deleted and regenerated them numerous times with icaros on and off, and the cache is fine.
I repeat, **the windows cache is working as intended**.

The problem literally only happens when icaros is doing its thing.
Icaros on = Thumbnails do not show for a long time, no matter what the windows cache is doing.
Icaros off= Thumbnails show fine with literally no issue at all.

Deleting and rebuilding the windows thumbnail caches and the icaros caches does not help.
