### ISSUE TITLE
Functionality for Non-Admin accounts

### ISSUE THREAD

**Issue by AlreadyFree** [Xanashi/Icaros#99] opened 2024-04-17 01:19 UTC
I've been using Icaros previously on Windows 7 and just updated Windows 10. I have my system set up where I have an administrator account but I use a non-administer account for normal operations. So I have access to administer credentials if asked but even so Icaros doesn't seem to have any effect in the non-admin account. It works fine in the admin account but making any changes in the Icaros config panel has no effect when logged in to the non-admin account. Strangely when I first installed icaros on the non-admin account and activated it it would load embedded cover art thumbnails for roughly half of my video files but not all. File properties don't work at all. I've tried building the database in the admin account and saving it in the same folder that is accessible from both accounts but the non-admin account still won't use the database. All the video files are stored an a secondary drive that is fully accessible from both accounts with read/write privileges. Is there any way to make this work?

**Comment by Xanashi** [comment] 2024-04-22 10:40
Hi AlreadyFree,

I don't see anything in your setup that should cause any issues with Icaros. 
When enabled, Icaros thumbnailing and properties actually affects the entire system, that is all user accounts. 
That's the way Microsoft designed it. So enabling thumbnailing and/or properties on your admin account, should make them work on both your accounts.

The Icaros Cache is a bit different, it's linked to the current logged in user account. So it should be set up separately on each account. And please note, the Icaros Cache can't be located on a network drive. It's not supported at the moment.

I've just tested all of the above on a fresh install of Windows 11 and it worked as expected. 
I will admit that there is a bug when installing Icaros on the second account. In my case it deactivated Icaros, which of course it shouldn't. I'll investigate that for sure.

Overall I can't reproduce your issue, so I will probably need more information, if you're still having problems.

**Comment by AlreadyFree** [comment] 2024-04-27 20:59
I'm really not sure what I did in all my trying different things but thumbnailing is working correctly now on both accounts but file properties are still only working on the administrator account. The filetypes are registered with Icaros in the registry. I'm not sure what additional information to provide to help you troubleshoot this. Are there any specific registry entries I should check that might be causing a problem?

**Comment by Xanashi** [comment] 2024-07-10 20:15
I guess the most likely issue is, that you have Icaros installed at a location, that is not accessible by all user accounts.
This can easily happen, if a user downloads the portable version, and places it anywhere within the Current User folder.
This would only allow Icaros to work on the Current User account.

The installer will place Icaros in C:\Program Files\ by default, which is a system wide folder, all users have access to.
Once you enable Icaros while it is in this folder, Icaros will be enabled on all user accounts.

It would probably also confuse IcarosConfig, if a user tried to run two portable versions on two different user accounts,
as the shell extensions are theoretically registered system wide, but can in that situation only be reached by the user account that 
enabled Icaros last.

**Comment by Xanashi** [comment] 2024-07-18 19:42
I'm going to close this ticket for now. Don't hesitate to reopen it if needed.

**Closed as completed by Xanashi** 2024-07-18 19:42 UTC
