### ISSUE TITLE
Enabling Icaros Properties affects Windows Photo Viewer and alters the image

### ISSUE THREAD

**Issue by HHH0003** [Xanashi/Icaros#133] opened 2024-10-13 16:21 UTC
### Activating Icaros Properties affects the Windows Photo Viewer and changes how images are rendered in the Photo App. An original horizontal image is displayed as a horizontal image within a vertical frame..  

**Ideally, enabling the Icaros Properties should not change the image display when using the Windows Photo App.  Hopefully a fix can be made.**

_Icaros has become an essential application following the release of iOS 18. Windows 11 versions 23H2/24H2 are unable to generate thumbnails or display the correct properties for .MOV files recently created on iPhones._  

**Image with Icaros Thumbnails enabled... Properties disabled.**

![Screenshot 2024-10-13 105252](https://github.com/user-attachments/assets/9756c888-cd04-4f18-b415-57e7fb21c63b)

**Image with Icaros Thumbnails and Properties both enabled.**

![Screenshot 2024-10-13 114129](https://github.com/user-attachments/assets/e794c4fd-8433-45d6-800f-aee6e4a14a96)

**Zip File of the .MOV file used in creating these screenshots.**

[20241013_144826000_iOS.zip](https://github.com/user-attachments/files/17356196/20241013_144826000_iOS.zip)

**Comment by Xanashi** [comment] 2024-10-15 19:03
Thank you for the really solid report, with images and sample included.
I believe I know what the problem is. I'll try to get a fix in for the upcoming release.

**Comment by Xanashi** [comment] 2024-10-20 12:46
This should be fixed in [v. 3.3.3 now](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3).
Could you give it a try and let me know.

**Comment by HHH0003** [comment] 2024-10-20 23:13
> This should be fixed in [v. 3.3.3 now](https://github.com/Xanashi/Icaros/releases/tag/v3.3.3). Could you give it a try and let me know.

### Yes, it worked perfectly... Thank you so much!  

**The problem with Windows Photo Viewer that's being discussed has persisted for quite some time, certainly for at least two years or more. Now, I can appreciate my iPhone photo and video library without worrying about a Windows Update disrupting functioning features.**

**Comment by Xanashi** [comment] 2024-11-01 12:06
So glad to hear it. 😊

**Closed as completed by Xanashi** 2024-11-01 12:06 UTC
Labels: bug, fixed
